apiVersion: v1
kind: Service
metadata:
  name: llm-service-latest
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      protocol: "TCP"
      name:  https
  selector:
    app.kubernetes.io/name: llm-service-latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mistral-7b
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: llm-service-latest
  template:
    metadata:
      labels:
        app.kubernetes.io/name: llm-service-latest
    spec:
      imagePullSecrets:
        - name: your-secret
      containers:
        - name: llm-service-latest
          image: "your.registry/llm-service-latest:latest"
          ports:
            - name: https
              containerPort: 8000
              protocol: TCP
          resources:
            limits:
              cpu: 1
              memory: 15G
            requests:
              cpu: 1
              memory: 10G
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
---
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: llm-service-latest-apirule
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: llm-service-latest
  service:
    name: llm-service-latest
    port: 8000
  rules:
    - path: /.*
      accessStrategies:
        - handler: oauth2_introspection
          config:
            required_scope: ["llm"]
      methods:
        - GET
        - POST