apiVersion: v1
kind: Service
metadata:
  name: llm-service-latest
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      protocol: "TCP"
      name:  https
  selector:
    app.kubernetes.io/name: llm-service-latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-service-latest
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: llm-service-latest
  template:
    metadata:
      labels:
        app.kubernetes.io/name: llm-service-latest
    spec:
      imagePullSecrets:
        - name: my-registry-secret
      containers:
        - name: llm-service-latest
          image: "felixschamoni1/llm:llm-service-latest"
          imagePullPolicy: Always
          ports:
            - name: https
              containerPort: 8000
              protocol: TCP
          resources:
            limits:
              cpu: 1
              memory: 3.5G
            requests:
              cpu: 1
              memory: 3.5G
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: LLM_MODEL
              value: "EleutherAI/pythia-70m-deduped"
---
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: llm-service-latest-apirule
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: llm-service-latest
  service:
    name: llm-service-latest
    port: 8000
  rules:
    - path: /.*
      accessStrategies:
        - handler: allow
          config: { }
      methods:
        - GET
        - POST